version: "3.7"
services:
    workspace:
        build:
            args:
                user: matheus
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - lazy

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 8009:80
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - lazy

    #conainter to run queues
    queue:
        build:
            args:
                user: matheus
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        command: 'php artisan queue:work'
        restart: unless-stopped
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - lazy


    db:
        image: mysql:5.7.22
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - 3315:3306
        networks:
            - lazy
    redis:
        image: redis:latest
        ports:
            - 6380:6379
        networks:
            - lazy

networks:
    lazy:
        driver: bridge
